Repository ITU-BDSA23-GROUP5/Chirp, pull requests merged in 2023-12, with the labels that each got.

#162 unique name and email
  src/Chirp.Core/Interfaces/IAuthorRepository.cs
  src/Chirp.Infrastructure/ChirpDBContext.cs
  src/Chirp.Infrastructure/Migrations/20231128143106_UniqueNameAndEmail.Designer.cs
  src/Chirp.Infrastructure/Migrations/20231128143106_UniqueNameAndEmail.cs
  src/Chirp.Infrastructure/Migrations/ChirpDBContextModelSnapshot.cs
  src/Chirp.Infrastructure/Repositories/AuthorRepository.cs
  src/Chirp.Web/Pages/Public/Public.cshtml.cs
  src/Chirp.Web/Pages/Public/UserTimeline.cshtml.cs
  test/Chirp.Infrastructure.Tests/AuthorRepositoryUnitTests.cs
Labels: enhancement

#165 Forgot to replace migrations
  src/Chirp.Infrastructure/Migrations/20231128143106_UniqueNameAndEmail.Designer.cs
  src/Chirp.Infrastructure/Migrations/20231128143106_UniqueNameAndEmail.cs
  src/Chirp.Infrastructure/Migrations/20231205120112_UniqueNameAndEmail.Designer.cs
  src/Chirp.Infrastructure/Migrations/20231205120112_UniqueNameAndEmail.cs
  src/Chirp.Infrastructure/Migrations/ChirpDBContextModelSnapshot.cs
Labels: enhancement

#183 Visible followers
  src/Chirp.Core/Interfaces/IAuthorRepository.cs
  src/Chirp.Infrastructure/Repositories/AuthorRepository.cs
  src/Chirp.Web/Pages/Public/UserTimeline.cshtml
  src/Chirp.Web/Pages/Public/UserTimeline.cshtml.cs
Labels: enhancement

#187 Initial report commit
  docs/images/readme.txt
  docs/report.md
  docs/sections/readme.txt
Labels: documentation

#180 Add download data button
  src/Chirp.Core/Interfaces/ICheepRepository.cs
  src/Chirp.Infrastructure/Repositories/CheepRepository.cs
  src/Chirp.Web/Pages/MyDataRecord.cs
  src/Chirp.Web/Pages/Private/User.cshtml
  src/Chirp.Web/Pages/Private/User.cshtml.cs
Labels: enhancement

#198 Fix: redirect to signout after deleting user
  src/Chirp.Web/Pages/Private/User.cshtml.cs
Labels: bug, enhancement

#202 Feature remove own cheeps
  src/Chirp.Core/Interfaces/ICheepRepository.cs
  src/Chirp.Infrastructure/Repositories/CheepRepository.cs
  src/Chirp.Web/Pages/Private/User.cshtml
  src/Chirp.Web/Pages/Private/User.cshtml.cs
  src/Chirp.Web/Pages/Public/Public.cshtml
  src/Chirp.Web/Pages/Public/Public.cshtml.cs
  src/Chirp.Web/Pages/Public/UserTimeline.cshtml
  src/Chirp.Web/Pages/Public/UserTimeline.cshtml.cs
  src/Chirp.Web/wwwroot/css/style.css
  test/Chirp.Infrastructure.Tests/CheepRepositoryUnitTests.cs
Labels: Feature

#207 Cheepfield is now empty after posting a chirp
  src/Chirp.Web/Pages/Public/Public.cshtml
  src/Chirp.Web/Pages/Public/UserTimeline.cshtml
Labels: enhancement

#204 feature trending page
  src/Chirp.Core/Interfaces/ICheepRepository.cs
  src/Chirp.Infrastructure/Repositories/CheepRepository.cs
  src/Chirp.Web/Pages/Public/Trending.cshtml
  src/Chirp.Web/Pages/Public/Trending.cshtml.cs
  src/Chirp.Web/Pages/Shared/_LoginPartial.cshtml
  test/Chirp.Infrastructure.Tests/CheepRepositoryUnitTests.cs
Labels: Feature

#208 delete cookie whether there or not
  src/Chirp.Web/Pages/Private/User.cshtml.cs
Labels: enhancement

#222 user activity diagrams
  docs/images/readme.txt
  docs/images/user-activity-diagrams/authenticated-user-activity-diagram.png
  docs/images/user-activity-diagrams/deleting-user-activity-diagram.png
  docs/images/user-activity-diagrams/unauthenticated-user-activity-diagram.png
  docs/report.md
  docs/sections/readme.txt
  docs/sections/user-activity-diagrams/authenticated-user-activity-diagram.puml
  docs/sections/user-activity-diagrams/deleting-user-activity-diagram.puml
  docs/sections/user-activity-diagrams/unauthenticated-user-activity-diagram.puml
Labels: documentation

#225 Report: build test release and deployment
  docs/images/build_test_release_and_deployment/build_and_test_workflow.png
  docs/images/build_test_release_and_deployment/deployment_workflow.png
  docs/images/build_test_release_and_deployment/release_razor_workflow.png
  docs/report.md
  docs/sections/build_test_release_and_deployment/build_and_test_workflow.txt
  docs/sections/build_test_release_and_deployment/deployment_workflow.txt
  docs/sections/build_test_release_and_deployment/release_razor_workflow.txt
Labels: documentation

#226 Report: LLMs
  docs/report.md
Labels: documentation

#232 Run test locally
  docs/report.md
Labels: documentation
